# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- manual

pool:
  vmImage: 'ubuntu-latest'

variables:
  poolname: '$(Build.BuildId)'
  URI: 'https://dev.azure.com/bansalpreeti1'
  targetSize: '1'

steps:

- task: Kubernetes@1
  displayName: 'kubectl get'
  name: clusterip
  inputs:
    kubernetesServiceEndpoint: sa
    command: get
    arguments: 'service azure-pipelines-pool -n 733-build -o=jsonpath={.status.loadBalancer.ingress[0].ip}'
    outputFormat: ''
  

- bash: |
   # Write your commands here
   
   echo 'Hello world'
   
   echo 'IP is '. $(clusterip.MyVar)
   
  displayName: 'Bash Script'

