trigger:
- manual

jobs:

################################################################################
- job: Connect_with_agent
################################################################################
  pool:
    name: '843'

  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
      
        echo 'Hello world in agent'
        which buildctl
  

