trigger:
- manual

jobs:

################################################################################
- job: Configure_poolprovider
################################################################################
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    poolname: '$(Build.BuildId)'
    URI: 'https://dev.azure.com/bansalpreeti1'
    targetSize: '1'
    sharedsecret: sharedsecret1234

  steps:
  - task: HelmInstaller@1
    displayName: 'Install Helm 2.15.0-rc.1'
    inputs:
      helmVersionToInstall: '2.15.0-rc.1'

  - task: HelmDeploy@0
    displayName: 'helm init'
    inputs:
      azureSubscription: 'RMDev (c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
      azureResourceGroup: 'processmonitor-rg'
      kubernetesCluster: testpool2
      command: init
      arguments: '--service-account tiller'

  - task: HelmDeploy@0
    displayName: 'helm ls'
    inputs:
      azureSubscription: 'RMDev (c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
      azureResourceGroup: 'processmonitor-rg'
      kubernetesCluster: testpool2

  - task: HelmDeploy@0
    displayName: 'helm install'
    inputs:
      azureSubscription: 'RMDev (c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
      azureResourceGroup: 'processmonitor-rg'
      kubernetesCluster: testpool2
      command: install
      chartType: FilePath
      chartPath: 'helm/k8s-poolprovider'
      releaseName: 'release-$(Build.BuildId)'
      overrideValues: '"vsts.VSTS_SECRET=sharedsecret1234","app.namespace=$(Build.BuildId)-build"'
      valueFile: 'helm/k8s-poolprovider/values.yaml'
      waitForExecution: false

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
      
        echo 'Hello world'
        sleep 25

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'RMDev (c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: 'az aks get-credentials --name testpool2 --resource-group processmonitor-rg'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
      
        Write-Host "Hello World"
      
        # Write your PowerShell commands here.
         
         Write-Host "Hello World"
         
         $ip=$(kubectl get service azure-pipelines-pool -n $(Build.BuildId)-build -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
         
         echo $ip
         
         $body = @{
               "name"="$(poolname)"
               "type"="Ignore"
               "acquireAgentEndpoint"="http://$($ip):8080/acquire"
               "releaseAgentEndpoint"="http://$($ip):8080/release"
               "getAgentDefinitionEndpoint"="http://$($ip):8080/definitions"
               "getAgentRequestStatusEndpoint"="http://$($ip):8080/definitions"
               "sharedSecret"="$(sharedSecret)"
             } | ConvertTo-Json
         
         $header = @{
              "Accept"="application/json"
         "Authorization"="Basic OmUzdGJpanBya3ZpYXJhZGhyM2Z0empkaDR3a2k2dnVhbHdtc3BuYWQ0amp6aGZwN3gzemE="
              "Content-Type"="application/json"
             } 
         
         $response = Invoke-WebRequest -Uri "$(URI)/_apis/distributedtask/agentclouds?api-version=5.0-preview" -Method 'Post' -Body $body -Headers $header
            
         Write-Host $response
         
         $jsonObj = ConvertFrom-Json $([String]::new($response.Content))
         
         Write-Host $jsonObj.agentCloudId
         
         $body1 = @{
               "name"="$(poolname)"
               "agentCloudId"=$jsonObj.agentCloudId
               "targetSize"=$(targetSize)
             } | ConvertTo-Json
         
             $response1 = Invoke-WebRequest -Uri "$(URI)/_apis/distributedtask/pools?api-version=5.0-preview" -Method 'Post' -Body $body1 -Headers $header
             Write-Host $response1
             $jsonObj1 = ConvertFrom-Json $([String]::new($response1.Content))

  - task: HelmDeploy@0
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscription: 'RMDev (c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
      azureResourceGroup: 'processmonitor-rg'
      kubernetesCluster: 'testpool2'
      command: 'ls'


################################################################################
- job: Connect_with_agent
################################################################################
  pool:
    vmImage: '$(Build.BuildId)'

  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
      
        echo 'Hello world in agent'
        which buildctl
  

  

